# Generated by Django 2.2 on 2019-04-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(max_length=50)),
                ('kind', models.CharField(max_length=80, null=True)),
                ('model', models.CharField(max_length=80, null=True)),
                ('year', models.DateField()),
                ('fuel_type', models.CharField(choices=[('lpg', 'LPG'), ('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric'), ('bifuel', 'Bifuel')], max_length=80, null=True)),
                ('transmission_type', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], max_length=80, null=True)),
                ('mileage', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('images', models.ImageField(null=True, upload_to='cars')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('onging', 'Onging'), ('end', 'End')], default='waiting', max_length=80, null=True)),
                ('auction_start_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-auction_start_time'],
            },
        ),
    ]
